steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/kinetic-engines-247005/kinetic-engines-analytics:21.04.25
  - --cache=true
  - --cache-ttl=6h

timeout: 4500s

options:
 logStreamingOption: STREAM_ON