steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/kinetic-engines-247005/kinetic-engines-analytics:21.11.28', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/kinetic-engines-247005/kinetic-engines-analytics:21.11.28']

images:
- 'gcr.io/kinetic-engines-247005/kinetic-engines-analytics:21.11.28'