steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/kinetic-engines/analytics:21.04.26', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/kinetic-engines/analytics:21.04.26']

images:
- 'gcr.io/kinetic-engines/analytics:21.04.26'