steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/kinetic-engines-247005/kinetic-engines-analytics:21.02.06",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/kinetic-engines-247005/kinetic-engines-analytics:21.02.06"]

timeout: 3600s

images:
  - "gcr.io/kinetic-engines-247005/kinetic-engines-analytics:21.02.06"
