steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/kinetic-engines-247005/kng/kinetic-engines-analytics:23.09.16', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/kinetic-engines-247005/kng/kinetic-engines-analytics:23.09.16']

images:
- 'europe-west1-docker.pkg.dev/kinetic-engines-247005/kng/kinetic-engines-analytics:23.09.16'

timeout: 1800s