steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/kinetic-engines-247005/kinetic-engines-analytics:21.01.17",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/kinetic-engines-247005/kinetic-engines-analytics:21.01.17"]

timeout: 1800s

images:
  - "gcr.io/kinetic-engines-247005/kinetic-engines-analytics:21.01.17"
