steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/kinetic-engines-247005/kinetic-engines-analytics:21.02.06
  - --cache=true
  - --cache-ttl=6h

timeout: 3600s

options:
 logStreamingOption: STREAM_ON

images:
  - "gcr.io/kinetic-engines-247005/kinetic-engines-analytics:21.02.06"
